- type: replace
  path: /networks/-
  value:
    name: default
    type: manual
    subnets:
    - az: z1
      range: ((terraform_outputs.private_subnet_az1_cidr))
      gateway: ((terraform_outputs.private_subnet_az1_gateway))
      reserved:
      - ((terraform_outputs.private_subnet_az1_reserved))
      - ((terraform_outputs.bosh_static_ip))
      dns: [((terraform_outputs.vpc_cidr_dns))]
      cloud_properties:
        subnet: ((terraform_outputs.private_subnet_az1))
        security_groups:
        - ((terraform_outputs.bosh_security_group))
    - az: z2
      range: ((terraform_outputs.private_subnet_az2_cidr))
      gateway: ((terraform_outputs.private_subnet_az2_gateway))
      reserved:
      - ((terraform_outputs.private_subnet_az2_reserved))
      dns: [((terraform_outputs.vpc_cidr_dns))]
      cloud_properties:
        subnet: ((terraform_outputs.private_subnet_az2))
        security_groups:
        - ((terraform_outputs.bosh_security_group))


# aws_subnet.az1_services

# - type: replace
#   path: /networks/-
#   value:
#   - name: services
#     type: manual
#     subnets:
#     - az: z1
#       range: ((terraform_outputs.az1_services)
#       gateway: ((terraform_outputs.services_subnet_az1_gateway))
#       reserved:
#       - ((terraform_outputs.services_subnet_az1_reserved))
#       static: ((terraform_outputs.services_static_ips))
#       dns: [((terraform_outputs.vpc_cidr_dns))]
#       cloud_properties:
#         subnet: ((terraform_outputs.services_subnet_az1))
#         security_groups:
#         - ((terraform_outputs.bosh_security_group))



- type: replace
  path: /disk_types/-
  value:
    name: nfs-volume
    disk_size: 64_000

- type: replace
  path: /compilation/network?
  value: default

# Ephemeral disks
- type: replace
  path: /disk_types/-
  value:
    name: default
    disk_size: 1024
- type: replace
  path: /disk_types/-
  value:
    name: 1GB
    disk_size: 1024
- type: replace
  path: /disk_types/-
  value:
    name: 5GB
    disk_size: 5120
- type: replace
  path: /disk_types/-
  value:
    name: 10GB
    disk_size: 10240
- type: replace
  path: /disk_types/-
  value:
    name: 50GB
    disk_size: 51200
- type: replace
  path: /disk_types/-
  value:
    name: 100GB
    disk_size: 102400
- type: replace
  path: /disk_types/-
  value:
    name: 500GB
    disk_size: 512000
- type: replace
  path: /disk_types/-
  value:
    name: 1TB
    disk_size: 1048576

- type: replace
  path: /vm_extensions/-
  value:
    name: 1GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 1024
- type: replace
  path: /vm_extensions/-
  value:
    name: 5GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 5120
- type: replace
  path: /vm_extensions/-
  value:
    name: 10GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 10240
- type: replace
  path: /vm_extensions/-
  value:
    name: 50GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 51200
- type: replace
  path: /vm_extensions/-
  value:
    name: 100GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 102400
- type: replace
  path: /vm_extensions/-
  value:
    name: 200GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 204800
- type: replace
  path: /vm_extensions/-
  value:
    name: 300GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 307200
- type: replace
  path: /vm_extensions/-
  value:
    name: 500GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 512000
- type: replace
  path: /vm_extensions/-
  value:
    name: 1TB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 1048576

# Load balancers
- type: replace
  path: /vm_extensions/-
  value:
    name: cf-router-network-properties
    cloud_properties:
      lb_target_groups: ((terraform_outputs.cf_router_target_groups))
- type: replace
  path: /vm_extensions/-
  value:
    name: cf-router-main-network-properties
    cloud_properties:
      lb_target_groups: ((terraform_outputs.cf_router_main_target_group))

- type: replace
  path: /vm_extensions/-
  value:
    name: diego-ssh-proxy-network-properties
    cloud_properties:
      elbs: [((terraform_outputs.diego_elb_name))]
- type: replace
  path: /vm_extensions/-
  value:
    name: cf-tcp-router-network-properties
    cloud_properties:
      lb_target_groups: ((terraform_outputs.tcp_lb_target_groups))
      security_groups: ((terraform_outputs.tcp_lb_security_groups))

# Instance profiles
- type: replace
  path: /vm_extensions/-
  value:
    name: blobstore-profile
    cloud_properties:
      iam_instance_profile: ((terraform_outputs.cf_blobstore_profile))
- type: replace
  path: /vm_extensions/-
  value:
    name: diego-platform-cell-profile
    cloud_properties:
      iam_instance_profile: ((terraform_outputs.platform_profile))