---
platform: linux

image_resource:
  type: registry-image
  source:
    aws_access_key_id: ((aws-key))
    aws_secret_access_key: ((aws-secret))
    repository: harden-concourse-task
    aws_region: us-gov-west-1
    semver_constraint: ">= 1.0.0"

inputs:
- name: cf-manifests
- name: timestamp

run:
  path: cf-manifests/ci/check-deployment-was-zdt.sh


